# Generated by Django 4.2.23 on 2025-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
    ]
