# Generated by Django 4.2.23 on 2025-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_remove_patient_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "chờ xác nhận"),
                    ("confirmed", "Đã xác nhận"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
