# Generated by Django 4.2.23 on 2025-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avata/"),
        ),
    ]
