# Generated by Django 4.2.23 on 2025-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
