# Generated by Django 4.2.23 on 2025-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0007_prescription_prescriptiondetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prescriptiondetail",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
