# Generated by Django 4.2.23 on 2025-09-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0008_prescription_diagnosis_prescriptiondetail_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("work", "Làm việc"), ("off", "Nghỉ")],
                        default="work",
                        max_length=10,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="userauths.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("doctor", "date")},
            },
        ),
    ]
