# Generated by Django 4.2.23 on 2025-12-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0009_doctorschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="specialization",
        ),
        migrations.CreateModel(
            name="DoctorSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("booked", "Booked")],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="userauths.doctor",
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        related_name="slots", to="userauths.specialty"
                    ),
                ),
            ],
            options={
                "unique_together": {("doctor", "start_time")},
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="userauths.doctorslot",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                related_name="doctors", to="userauths.specialty"
            ),
        ),
    ]
