# Generated by Django 4.2.23 on 2025-12-11 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "userauths",
            "0010_specialty_remove_doctor_specialization_doctorslot_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorslot",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
