# Generated by Django 4.2.23 on 2025-12-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0011_doctorslot_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="slot",
        ),
        migrations.DeleteModel(
            name="DoctorSlot",
        ),
    ]
