# Generated by Django 4.2.23 on 2025-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0012_remove_appointment_slot_delete_doctorslot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="specialty_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="appointment",
            table="appointment",
        ),
    ]
