# Generated by Django 4.2.23 on 2025-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userauths",
            "0013_remove_appointment_doctor_remove_appointment_patient_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="appointment",
            table="userauths_appointment",
        ),
    ]
